import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import Navbar from "@/components/LayoutComponents/Navbar/Navbar";
import WrapperSidePanelModalNav from "@/components/LayoutComponents/WrapperSidePanModalNav/WrapperSidePanelModalNav";
import {ModalProvider} from "@/components/LayoutComponents/ModalContext/ModalContext";
import {FilterProvider} from "@/components/filters/FilterContext";
import ReduxProvider from "@/components/ReduxProvider";
import InitSession from "@/components/initSession/InitSession";

export const metadata: Metadata = {
    title: "Yourika",
    description: "Generated by Yuriy Bilyk",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className="flex flex-col min-h-screen p-0">
        <ReduxProvider>
        <FilterProvider>
            <ModalProvider>
                <InitSession/>
                <Navbar/>
                <WrapperSidePanelModalNav/>
                <div className="flex flex-1 p">
                    <main className="flex-1 bg-gray-50 bg-white px-20">
                        {children}
                    </main>
                </div>
            </ModalProvider>
        </FilterProvider>
        </ReduxProvider>
        </body>
        </html>
    );
}