version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - backend
    depends_on:
      - redis
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - backend
networks:
  backend:
